import Head from "next/head";
import Link from "next/link";
import React from "react";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import profile from "../assets/profile.jpg";
import Image from "next/image";
const About = () => {
  const router = useRouter();
  const style = {
    color: router.asPath === "/about" ? "lightblue" : "white",
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <div className={styles.logo}>Long.</div>
          <div className={styles.menu}>
            <Link href={"/"}>
              <a>work</a>
            </Link>
            <Link href={"/about"}>
              <a style={style}>about</a>
            </Link>
          </div>
        </div>
        <div>
          <div className={styles.wrapper1}>
            <div className={styles.box1}>
              <h1>hello, i&apos;m Cheulong</h1>I am currently a web developer. I
              am working on a project focus on communication.
              <br />
              <br />
              <Link href="https://drive.google.com/uc?export=download&id=1a5vkANF5rMYuTb6nfQlKeYXwC7H7OgW4">
                <a style={{ textDecoration: "underline" }}>resume</a>
              </Link>
            </div>
            <Image
              src={profile}
              layout={"fixed"}
              width={300}
              height={400}
              alt=""
            />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>searcheulong@gmail.com</footer>
    </div>
  );
};

export default About;
