import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import mountains from "../assets/1.png";
import mountains1 from "../assets/2.png";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const style = {
    color: router.asPath === "/" ? "lightblue" : "white",
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <div className={styles.logo}>Long.</div>
          <div className={styles.menu}>
            <Link href={"/"}>
              <a style={style}>work</a>
            </Link>
            <Link href={"/about"}>
              <a>about</a>
            </Link>
          </div>
        </div>
        <div>
          <div className={styles.wrapper}>
            <div className={styles.box}>
              <Link href={"/projects/1"}>
                <Image src={mountains} layout={"responsive"} alt="" />
              </Link>
            </div>
            <div className={styles.box}>
              <Link href={"/projects/2"}>
                <Image src={mountains1} layout={"responsive"} alt="" />
              </Link>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>searcheulong@gmail.com</footer>
    </div>
  );
}
